import type { StoryConfig } from './config.types'

/* ============================================================================
   ✦ THE ONLY FILE YOU NEED TO EDIT ✦
   ----------------------------------------------------------------------------
   Drop real assets into /public (e.g. public/photos, public/stickers,
   public/audio) and point the paths below at them. Leave a path out and a
   hand-drawn placeholder is shown instead — the layout never shifts when you
   later add the real photo. All visible copy is in English; change freely.
   ============================================================================ */

export const config: StoryConfig = {
  // — Who this is for —
  friendName: 'Pawa Babi 🐖🐷',
  age: 20,

  // — Hero photo (centre stage). Omit `heroPhoto` to use the placeholder.
  heroPhoto: 'images/main_photo.jpg',

  // — Candles on the cake —
  candleCount: 5,
  confettiIntensity: 'high',

  // — The two typed lines of the intro —
  dialogue: {
    darkLine: 'why is it so dark in here??',
    switchHint: 'click the switch to light up the room',
  },

  // — The letter inside the envelope —
  greeting: {
    salutation: 'To Human that live far away 🐖,',
    body: [
      'สุขสันต์วันเกิดนะเพื่อนรัก! 🎂',
      'ขอให้รวยๆ ซวยๆ ไปไกลๆ มีเงินมีทองกองท่วมหัว หน้าเด็กลงทุกปี แต่อายุไม่ลงนะจ๊ะ 555 ขอให้สุขภาพแข็งแรง กินเท่าไหร่ก็ไม่อ้วน 😂',
      'รักนะ เพื่อนแก่... เอ๊ย เพื่อนรัก! 🎉',
      'generated by GPT 🤖, so please forgive me if there are any mistakes😛',
    ],
    signoff: 'With love,',
    // ↓ YOUR name — the handwritten signature at the bottom of the letter.
    signature: 'Lord Dave 😼👑',
  },

  // — Scattered memory stickers. Add `src` to use a real photo; omit for a
  //   drawn placeholder. `together: true` marks a "you + friend" shot. —
  stickers: [
    {
      caption: 'throwback',
      shape: 'polaroid',
      tapeStyle: 'single',
      src: 'images/IMG_20260628_083417.jpg',
    },
    {
      caption: 'the birthday star',
      shape: 'polaroid',
      tapeStyle: 'single',
      src: 'images/IMG_20260628_083558.jpg',
    },
    {
      caption: 'our adventure',
      together: true,
      shape: 'torn',
      tapeStyle: 'tack',
      src: 'images/IMG_20260628_083344.jpg',
    },
    {
      caption: 'us together',
      together: true,
      shape: 'polaroid',
      tapeStyle: 'cross',
      src: 'images/IMG_20260628_083455.jpg',
    },
  ],

  // — Audio. Drop files in /public/audio and uncomment. Music only starts after
  //   the switch is flipped (a user gesture), which is required on iOS. —
  musicPath: 'audio/thai_hbd_song.mp3',
  // sfx: {
  //   switch: 'audio/click.mp3',
  //   pop: 'audio/pop.mp3',
  //   whoosh: 'audio/whoosh.mp3',
  //   sealCrack: 'audio/seal.mp3',
  //   rustle: 'audio/rustle.mp3',
  // },

  // — Optional theme overrides (CSS custom properties, no leading dashes) —
  // theme: { rose: '#ff6f91', 'lit-gold': '#d8b04e' },
}

export default config
